server {
    listen 80;
    root /usr/share/nginx/html;

    location /mytracks-ui/ {
        try_files $uri $uri/ /mytracks-ui/index.html;
    }

    location = / {
        return 301 /mytracks-ui/;
    }
}
