spring.application.name=mytracks

spring.datasource.url=jdbc:postgresql://localhost:5432/mytracks
spring.datasource.username=${DB_USERNAME:mytracks}
spring.datasource.password=${DB_PASSWORD:mytracks}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.locations=classpath:db/migration

spring.security.oauth2.client.registration.google.client-id=${OAUTH2_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH2_CLIENT_SECRET}

auth.allowed-emails=*
