ALTER TABLE tracks
    ALTER COLUMN distance_meters TYPE DOUBLE PRECISION,
    ALTER COLUMN ascent_meters   TYPE DOUBLE PRECISION,
    ALTER COLUMN descent_meters  TYPE DOUBLE PRECISION,
    ALTER COLUMN avg_speed_ms    TYPE DOUBLE PRECISION,
    ALTER COLUMN max_speed_ms    TYPE DOUBLE PRECISION;
